- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(2a1212b0-6d53-4799-a2be-a004611dd427)'
    appType: 'webAppLinux'
    WebAppName: 'SlothFlyingWeb'
    deployToSlotOrASE: true
    ResourceGroupName: 'SlothFlyingWebResourceGroup'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'DOTNETCORE|3.1'